import { ArrowLeftIcon, ArrowRightIcon, BurgerIcon, CardsIcon, CloverIcon, CoupleIcon, CustomIcon, DiceIcon, DragIcon, FamilyIcon, FoodIcon, FriendIcon, GameIcon, GifIcon, HelpIcon, HomeIcon, JokeIcon, LuckyDateIcon, MovieIcon, PlusIcon, RandomIcon, RestaurantIcon, RocketIcon, ScratchIcon, SportIcon, TrashIcon, WheelIcon } from "@src/components/Icons";

export enum Icon {
    ARROW_LEFT = 'arrow_left',
    ARROW_RIGHT = 'arrow_right',
    BURGER = 'burger',
    CLOVER = "clover",
    COUPLE = "couple",
    CUSTOM = "custom",
    CARDS = "cards",
    DICE = "dice",
    DRAG = "drag",
    FAMILY = 'family',
    FOOD = 'food',
    FRIEND = 'friend',
    GAME = 'game',
    GIF = 'gif',
    HELP = 'help',
    HOME = 'home',
    JOKE = 'joke',
    LOGO = 'lucky_date',
    MOVIE = 'movie',
    PLUS = 'plus',
    RANDOM = "random",
    RESTAURANT = "restaurant",
    ROCKET = "rocket",
    SCRATCH = "scratch",
    SPORT = "sport",
    TRASH = "trash",
    WHEEL = "wheel",
}

const IconComponents = {
    [Icon.ARROW_LEFT]: ArrowLeftIcon,
    [Icon.ARROW_RIGHT]: ArrowRightIcon,
    [Icon.BURGER]: BurgerIcon,
    [Icon.CARDS]: CardsIcon,
    [Icon.CLOVER]: CloverIcon,
    [Icon.COUPLE]: CoupleIcon,
    [Icon.CUSTOM]: CustomIcon,
    [Icon.DICE]: DiceIcon,
    [Icon.DRAG]: DragIcon,
    [Icon.FAMILY]: FamilyIcon,
    [Icon.FOOD]: FoodIcon,
    [Icon.FRIEND]: FriendIcon,
    [Icon.GAME]: GameIcon,
    [Icon.GIF]: GifIcon,
    [Icon.HELP]: HelpIcon,
    [Icon.HOME]: HomeIcon,
    [Icon.LOGO]: LuckyDateIcon,
    [Icon.MOVIE]: MovieIcon,
    [Icon.PLUS]: PlusIcon,
    [Icon.JOKE]: JokeIcon,
    [Icon.RANDOM]: RandomIcon,
    [Icon.RESTAURANT]: RestaurantIcon,
    [Icon.ROCKET]: RocketIcon,
    [Icon.SCRATCH]: ScratchIcon,
    [Icon.SPORT]: SportIcon,
    [Icon.TRASH]: TrashIcon,
    [Icon.WHEEL]: WheelIcon,
};

export default IconComponents;